name: CI
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: build package
        run: |-
          python setup.py sdist
      - name: build package
        run: |-
          python setup.py bdist
      - name: install twine
        run: |-
          pip install twine
      - name: install twine
        run: |-
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
