name: CI
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: build package
        run: |-
          python3 -m pip install --upgrade twine build
      - name: build package
        run: |-
          python3 -m build
      - name: install twine
        run: |-
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} -r django-recaptcha-enterprise
